on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run npm dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Run component rust-std
        run: rustup target add aarch64-apple-darwin
      - name: Run build universal
        run: npm run build:macOS-universal
